"""
CLI entry points for fastcausal.

Provides commands: parse, run, paths, report, analyze.
"""

import click

from fastcausal import __version__


@click.group()
@click.version_option(version=__version__)
def main():
    """fastcausal - Fast, easy-to-use causal discovery analysis tools."""
    pass


@main.command()
@click.argument("output", default="config.yaml", type=click.Path())
def init(output):
    """Generate a sample config.yaml with commented examples."""
    import os

    if os.path.exists(output):
        click.confirm(f"{output} already exists. Overwrite?", abort=True)

    sample_config = """\
# fastcausal config.yaml (v5.0)
# Generated by: fastcausal init
#
# Usage:
#   fastcausal parse --config config.yaml
#   fastcausal run   --config config.yaml
#   fastcausal paths --config config.yaml
#   fastcausal report --config config.yaml

GLOBAL:
  version: 5.0
  name: my_project
  title: "My Causal Discovery Analysis"
  # header: "Optional header text for reports"

  # Directory layout (relative to this config file)
  directories:
    rawdatadir: data_raw       # raw input data
    datadir: data              # preprocessed data (output of 'parse')
    output: output             # analysis results (output of 'run')

  # Cases to skip during batch processing (by folder name)
  # cases_ignore:
  #   - bad_case_01
  #   - incomplete_case_02

# ─── Data preparation ('fastcausal parse') ──────────────────────────
PREP:
  datafile: raw_data.csv       # source CSV in rawdatadir

  # Minimum data requirements
  variables:
    min_rows: 40               # minimum rows after processing
    min_raw_rows: 20           # minimum rows in raw data

  # overwrite_prior: true      # regenerate prior.txt each run (default: true)

  # Processing steps are applied in order. Use steps_global for the entire
  # dataset (before splitting by case) and steps_case for per-case processing.
  # Each step has an 'op' (operation name) and an optional 'arg'.
  #
  # Available operations:
  #
  #   ── Column operations ──
  #   - op: keep                       # keep only these columns
  #     arg: [col1, col2, col3]
  #   - op: drop                       # drop these columns
  #     arg: [col_to_remove]
  #   - op: rename                     # rename columns
  #     arg: { old_name: new_name }
  #
  #   ── Row operations ──
  #   - op: sort                       # sort rows by column
  #     arg: date
  #   - op: query                      # filter rows (pandas query syntax)
  #     arg: "age > 18 and status == 'active'"
  #   - op: droprows                   # drop rows where column has these values
  #     arg: { status: [invalid, test] }
  #   - op: keeprows                   # keep only rows where column has these values
  #     arg: { group: [treatment, control] }
  #
  #   ── Missing data ──
  #   - op: missing_value              # handle missing values globally
  #     arg: drop                      #   "drop" = remove rows with any NaN
  #                                    #   "pad"  = forward-fill NaNs
  #   - op: missing_value_columns      # fill NaNs per column with a specific value
  #     arg: { score: 0, rating: 3.0 }
  #
  #   ── Value transformations ──
  #   - op: recode                     # remap values (all values must be mapped)
  #     arg:
  #       severity: { "none": 0, "mild": 1, "moderate": 2, "severe": 3 }
  #   - op: replace_values             # replace specific values (others unchanged)
  #     arg:
  #       score: { -99: null, -88: null }
  #   - op: reverse                    # reverse-score: new = max_val - old
  #     arg: { neg_item1: 5, neg_item2: 5 }
  #
  #   ── Computed columns ──
  #   - op: sum_columns                # create column as sum of others
  #     arg: { name: total, columns: [item1, item2, item3] }
  #   - op: mean_columns               # create column as mean of others
  #     arg: { name: avg_mood, columns: [happy, calm, relaxed] }
  #   - op: max_columns                # create column as max of others
  #     arg: { name: worst_symptom, columns: [pain, fatigue, nausea] }
  #
  #   ── Causal prep ──
  #   - op: add_lag                    # add lagged columns (suffix '_lag')
  #   - op: standardize                # z-score standardize all numeric columns
  #
  #   ── Output ──
  #   - op: save                       # save current state to CSV
  #     arg:
  #       dir: data                    #   output directory (relative to project)
  #       stub: .csv                   #   filename suffix: {case_label}{stub}
  #       min_rows: 40                 #   skip save if fewer rows than this

  # Global processing steps (applied to entire dataset before case split)
  # steps_global:
  #   - op: sort
  #     arg: date
  #   - op: keep
  #     arg: [id, date, mood, sleep, activity]
  #   - op: missing_value
  #     arg: drop

  # Per-case processing steps (applied to each case after splitting by 'id')
  # steps_case:
  #   - op: add_lag
  #   - op: standardize
  #   - op: save
  #     arg: { dir: data, stub: .csv, min_rows: 40 }

# ─── Causal discovery ('fastcausal run') ────────────────────────────
CAUSAL:
  # Algorithm selection
  # Options: pc, fges, gfci, boss, boss_fci, grasp, grasp_fci
  algorithm: gfci

  # ── Common parameters ──
  alpha: 0.05                  # significance level for independence tests
                               # (used by: pc, gfci, boss_fci, grasp_fci)
  penalty_discount: 1.0       # BIC penalty multiplier; higher = sparser graph
                               # (used by: fges, gfci, boss, boss_fci, grasp, grasp_fci)

  # ── Data preprocessing ──
  standardize_cols: true       # standardize columns before running (recommended)
  jitter: 0.0                  # add random jitter to break ties (0 = off)

  # ── Prior knowledge ──
  # knowledge: prior.txt       # path to Tetrad-format knowledge file (in datadir)

  # ── Advanced parameters (algorithm-specific) ──
  depth: -1                    # max conditioning set size (-1 = unlimited)
                               # (used by: pc, gfci, boss_fci, grasp_fci)
  max_degree: -1               # max node degree (-1 = unlimited)
                               # (used by: fges, gfci)

  # Parameters below are not yet exposed in config but available via the
  # Python API (fc.run_search):
  #
  # FGES:
  #   faithfulness_assumed: true
  #
  # BOSS / BOSS-FCI:
  #   use_bes: false           # use Backward Equivalence Search
  #   num_starts: 1            # number of random restarts
  #
  # GRaSP:
  #   depth: 3                 # GRaSP-specific search depth
  #   uncovered_depth: 1
  #   non_singular_depth: 1
  #   num_starts: 1
  #
  # GRaSP-FCI:
  #   grasp_depth: 3           # GRaSP search depth within FCI
  #   complete_rule_set: true  # use complete FCI orientation rules
  #   num_starts: 1

  # out: output                # override output directory

# ─── SEM fitting ────────────────────────────────────────────────────
SEM:
  # Which edge types to include as regression paths in the SEM model
  # Default includes directed (-->) and partially oriented (o->) edges.
  # Bidirectional (<->) and undirected (---) edges are excluded by default
  # because they represent possible latent confounding that cannot be
  # properly modeled as simple covariances.
  # include_model_edges:
  #   - ["-->", "~"]
  #   - ["o->", "~"]

  plotting:
    # label: true              # show edge labels (coefficients)
    # show_pvalue: true        # show p-values on edges
    # min_pvalue: 1            # only label edges with p-value <= this
    # fontname: Helvetica
    # plot_all_edges: false    # if false, only plot edges in the SEM model
    # label_edge_types:        # edge types to label with SEM estimates
    #   - "-->"
    #   - "o->"
    #   - "o-o"

# ─── Effect size heatmaps ('fastcausal paths') ─────────────────────
# PATHS:
#   effectsize:
#     PHQ9:                    # destination variable
#       src:                   # source variables to trace paths from
#         - worry_scale
#         - PANAS_NA
#         - alcohol_bev
#       title: "Effect sizes on PHQ9"
#       grid:
#         plot: true
#         plotname: "heatmap_phq9"
#         widthInches: 16.0
#         heightInches: 8.0
#         labelsize: 10
#         titleSize: 18
#         xrotate: 45
#       # cases:               # optional: filter to specific cases
#       #   - case_01
#       #   - case_02
"""

    with open(output, "w") as f:
        f.write(sample_config)

    click.echo(f"Sample config written to: {output}")
    click.echo("Edit the file to match your project, then run:")
    click.echo(f"  fastcausal parse --config {output}")
    click.echo(f"  fastcausal run   --config {output}")


@main.command()
@click.option("--config", required=True, type=click.Path(exists=True), help="Path to config.yaml")
def parse(config):
    """Prepare and preprocess data from a config file."""
    from fastcausal.pipeline.config import load_config
    from fastcausal.pipeline.parse import run_parse

    cfg = load_config(config)
    run_parse(cfg)


@main.command()
@click.option("--config", required=True, type=click.Path(exists=True), help="Path to config.yaml")
@click.option("--start", default=0, help="Start index for case processing")
@click.option("--end", default=-1, help="End index for case processing (-1 = all)")
@click.option("--list", "list_cases", is_flag=True, help="List cases without processing")
def run(config, start, end, list_cases):
    """Run causal discovery analysis."""
    from fastcausal.pipeline.config import load_config
    from fastcausal.pipeline.batch import run_batch

    cfg = load_config(config)
    run_batch(cfg, start=start, end=end, list_cases=list_cases)


@main.command()
@click.option("--config", required=True, type=click.Path(exists=True), help="Path to config.yaml")
def paths(config):
    """Compute path effect sizes and generate heatmaps."""
    from fastcausal.pipeline.config import load_config
    from fastcausal.pipeline.paths import run_paths

    cfg = load_config(config)
    run_paths(cfg)


@main.command()
@click.option("--config", required=True, type=click.Path(exists=True), help="Path to config.yaml")
@click.option("--mode", default="1wide", type=click.Choice(["1wide", "2wide", "3wide"]), help="Report layout mode")
@click.option("--stub", default="_label.png", help="Image filename suffix to include")
def report(config, mode, stub):
    """Generate analysis report document."""
    from fastcausal.pipeline.config import load_config
    from fastcausal.pipeline.report import run_report

    cfg = load_config(config)
    run_report(cfg, mode=mode, stub=stub)


@main.group()
def varlist():
    """Inspect columns and data quality of a CSV/Excel file."""
    pass


@varlist.command()
@click.argument("datafile", type=click.Path(exists=True))
@click.option("--indent", default=8, type=int, help="Number of leading spaces")
@click.option("--lag-suffix", default="_", help="Suffix indicating a lag column")
def cols(datafile, indent, lag_suffix):
    """List columns in formats suitable for config files."""
    import numpy as np
    import pandas as pd

    df = _read_datafile(datafile)
    columns = [c for c in df.columns if c != "Unnamed: 0"]
    sp = " " * indent

    click.echo("── YAML list (- var) ──")
    for var in columns:
        click.echo(f"{sp}- {var}")

    click.echo("\n── Plain list ──")
    for var in columns:
        click.echo(f"{sp}{var}")

    click.echo("\n── Comma-separated ──")
    for var in columns:
        click.echo(f"{sp}{var},")

    click.echo("\n── With lag pairs ──")
    for var in columns:
        if var[-1] != lag_suffix:
            click.echo(f"{sp}{var},")
            click.echo(f"{sp}{var}{lag_suffix},")

    click.echo("\n── Rename section ──")
    click.echo("    -\n        op: rename\n        arg:")
    for var in columns:
        click.echo(f"{sp}{var}: {var}")

    click.echo("\n── Prior knowledge file ──")
    click.echo("/knowledge\n")
    click.echo("addtemporal")
    click.echo("1 " + " ".join(f"{v}_lag" for v in columns))
    click.echo("2 " + " ".join(columns))
    click.echo("\nforbiddirect\n\nrequiredirect\n")


@varlist.command()
@click.argument("datafile", type=click.Path(exists=True))
@click.option("--thresh", default=0, type=int, help="Completeness threshold %% to save filtered file (0 = skip)")
def check(datafile, thresh):
    """Check data quality: null counts and threshold-based column filtering."""
    import os

    import numpy as np
    import pandas as pd

    df = _read_datafile(datafile)
    columns = [c for c in df.columns if c != "Unnamed: 0"]
    df = df[columns]

    # Per-column completeness
    results = []
    for col in columns:
        total = len(df[col])
        clean = df[col].dropna().shape[0]
        results.append({"column": col, "total": total, "clean": clean, "percent": clean / total * 100.0})

    summary = pd.DataFrame(results)
    summ_path = datafile.rsplit(".", 1)[0] + "_colsumm.csv"
    summary.to_csv(summ_path, index=False)
    click.echo(f"Column summary saved to: {summ_path}")

    # Threshold sweep
    for t in range(50, 105, 5):
        keep_cols = summary.loc[summary["percent"] >= t, "column"].tolist()
        cleaned = df[keep_cols].dropna()
        pct_rows = len(cleaned) / len(df) * 100
        click.echo(f"  thresh:{t:3d}  rows:{len(cleaned):>6d}/{len(df)}  ({pct_rows:5.1f}%)  cols:{len(keep_cols)}")

    # Save filtered file at requested threshold
    if thresh > 0:
        keep_cols = summary.loc[summary["percent"] >= thresh, "column"].tolist()
        cleaned = df[keep_cols].dropna()
        out_path = datafile.rsplit(".", 1)[0] + f"_thresh{thresh}.csv"
        cleaned.to_csv(out_path, index=False)
        click.echo(f"\nFiltered data saved to: {out_path}")
        click.echo(f"Columns kept at {thresh}% threshold:")
        for col in keep_cols:
            click.echo(f"        - {col}")


def _read_datafile(path):
    """Read a CSV or Excel file into a DataFrame."""
    import os

    import numpy as np
    import pandas as pd

    ext = os.path.splitext(path)[1].lower()
    if ext == ".csv":
        df = pd.read_csv(path, encoding="Latin-1")
    elif ext in (".xlsx", ".xls"):
        df = pd.read_excel(path, engine="openpyxl")
    else:
        raise click.ClickException(f"Unsupported file type: {ext}. Use .csv or .xlsx")
    df.replace("#NULL!", np.nan, inplace=True)
    return df


@main.command()
@click.argument("datafile", type=click.Path(exists=True))
@click.option("--algorithm", default="gfci", type=click.Choice(["pc", "fges", "gfci"]), help="Causal discovery algorithm")
@click.option("--alpha", default=0.05, type=float, help="Significance level")
@click.option("--penalty-discount", default=1.0, type=float, help="BIC penalty multiplier")
@click.option("--output", default=".", type=click.Path(), help="Output directory")
def analyze(datafile, algorithm, alpha, penalty_discount, output):
    """Quick single-file causal analysis."""
    import os
    import pandas as pd
    from fastcausal import FastCausal

    fc = FastCausal()
    df = fc.load_csv(datafile)

    kwargs = {}
    if algorithm in ("pc", "gfci"):
        kwargs["alpha"] = alpha
    if algorithm in ("fges", "gfci"):
        kwargs["penalty_discount"] = penalty_discount

    results, dg = fc.run_search(df, algorithm=algorithm, run_sem=False, **kwargs)

    os.makedirs(output, exist_ok=True)
    graph_path = os.path.join(output, os.path.splitext(os.path.basename(datafile))[0])
    if results["edges"]:
        fc.save_graph(dg, graph_path, plot_format="png")
        click.echo(f"Graph saved to: {graph_path}")

    click.echo(f"Edges found: {len(results.get('edges', []))}")
    for edge in results.get("edges", []):
        click.echo(f"  {edge}")
