"""
CLI entry points for fastcausal.

Provides commands: parse, run, paths, report, analyze.
"""

import click


@click.group()
@click.version_option()
def main():
    """fastcausal - Fast, easy-to-use causal discovery analysis tools."""
    pass


@main.command()
@click.argument("output", default="config.yaml", type=click.Path())
def init(output):
    """Generate a sample config.yaml with commented examples."""
    import os

    if os.path.exists(output):
        click.confirm(f"{output} already exists. Overwrite?", abort=True)

    sample_config = """\
# fastcausal config.yaml (v5.0)
# Generated by: fastcausal init
#
# Usage:
#   fastcausal parse --config config.yaml
#   fastcausal run   --config config.yaml
#   fastcausal paths --config config.yaml
#   fastcausal report --config config.yaml

GLOBAL:
  version: 5.0
  name: my_project
  title: "My Causal Discovery Analysis"
  # header: "Optional header text for reports"

  # Directory layout (relative to this config file)
  directories:
    rawdatadir: data_raw       # raw input data
    datadir: data              # preprocessed data (output of 'parse')
    output: output             # analysis results (output of 'run')

  # Cases to skip during batch processing (by folder name)
  # cases_ignore:
  #   - bad_case_01
  #   - incomplete_case_02

# ─── Data preparation ('fastcausal parse') ──────────────────────────
PREP:
  datafile: raw_data.csv       # source CSV in rawdatadir

  # Minimum data requirements
  variables:
    min_rows: 40               # minimum rows after processing
    min_raw_rows: 20           # minimum rows in raw data

  # overwrite_prior: true      # regenerate prior.txt each run (default: true)

  # Global processing steps (applied to entire dataset)
  # steps_global:
  #   - step_name: "filter_dates"
  #     params: { start: "2024-01-01", end: "2024-12-31" }

  # Per-case processing steps
  # steps_case:
  #   - step_name: "add_lags"
  #     params: { n_lags: 1 }

# ─── Causal discovery ('fastcausal run') ────────────────────────────
CAUSAL:
  # Algorithm selection
  # Options: pc, fges, gfci, boss, boss_fci, grasp, grasp_fci
  algorithm: gfci

  # ── Common parameters ──
  alpha: 0.05                  # significance level for independence tests
                               # (used by: pc, gfci, boss_fci, grasp_fci)
  penalty_discount: 1.0       # BIC penalty multiplier; higher = sparser graph
                               # (used by: fges, gfci, boss, boss_fci, grasp, grasp_fci)

  # ── Data preprocessing ──
  standardize_cols: true       # standardize columns before running (recommended)
  jitter: 0.0                  # add random jitter to break ties (0 = off)

  # ── Prior knowledge ──
  # knowledge: prior.txt       # path to Tetrad-format knowledge file (in datadir)

  # ── Advanced parameters (algorithm-specific) ──
  depth: -1                    # max conditioning set size (-1 = unlimited)
                               # (used by: pc, gfci, boss_fci, grasp_fci)
  max_degree: -1               # max node degree (-1 = unlimited)
                               # (used by: fges, gfci)

  # Parameters below are not yet exposed in config but available via the
  # Python API (fc.run_search):
  #
  # FGES:
  #   faithfulness_assumed: true
  #
  # BOSS / BOSS-FCI:
  #   use_bes: false           # use Backward Equivalence Search
  #   num_starts: 1            # number of random restarts
  #
  # GRaSP:
  #   depth: 3                 # GRaSP-specific search depth
  #   uncovered_depth: 1
  #   non_singular_depth: 1
  #   num_starts: 1
  #
  # GRaSP-FCI:
  #   grasp_depth: 3           # GRaSP search depth within FCI
  #   complete_rule_set: true  # use complete FCI orientation rules
  #   num_starts: 1

  # out: output                # override output directory

# ─── SEM fitting ────────────────────────────────────────────────────
SEM:
  # Which edge types to include as regression paths in the SEM model
  # Default includes directed (-->) and partially oriented (o->) edges.
  # Bidirectional (<->) and undirected (---) edges are excluded by default
  # because they represent possible latent confounding that cannot be
  # properly modeled as simple covariances.
  # include_model_edges:
  #   - ["-->", "~"]
  #   - ["o->", "~"]

  plotting:
    # label: true              # show edge labels (coefficients)
    # show_pvalue: true        # show p-values on edges
    # min_pvalue: 1            # only label edges with p-value <= this
    # fontname: Helvetica
    # plot_all_edges: false    # if false, only plot edges in the SEM model
    # label_edge_types:        # edge types to label with SEM estimates
    #   - "-->"
    #   - "o->"
    #   - "o-o"

# ─── Effect size heatmaps ('fastcausal paths') ─────────────────────
# PATHS:
#   effectsize:
#     PHQ9:                    # destination variable
#       src:                   # source variables to trace paths from
#         - worry_scale
#         - PANAS_NA
#         - alcohol_bev
#       title: "Effect sizes on PHQ9"
#       grid:
#         plot: true
#         plotname: "heatmap_phq9"
#         widthInches: 16.0
#         heightInches: 8.0
#         labelsize: 10
#         titleSize: 18
#         xrotate: 45
#       # cases:               # optional: filter to specific cases
#       #   - case_01
#       #   - case_02
"""

    with open(output, "w") as f:
        f.write(sample_config)

    click.echo(f"Sample config written to: {output}")
    click.echo("Edit the file to match your project, then run:")
    click.echo(f"  fastcausal parse --config {output}")
    click.echo(f"  fastcausal run   --config {output}")


@main.command()
@click.option("--config", required=True, type=click.Path(exists=True), help="Path to config.yaml")
def parse(config):
    """Prepare and preprocess data from a config file."""
    from fastcausal.pipeline.config import load_config
    from fastcausal.pipeline.parse import run_parse

    cfg = load_config(config)
    run_parse(cfg)


@main.command()
@click.option("--config", required=True, type=click.Path(exists=True), help="Path to config.yaml")
@click.option("--start", default=0, help="Start index for case processing")
@click.option("--end", default=-1, help="End index for case processing (-1 = all)")
@click.option("--list", "list_cases", is_flag=True, help="List cases without processing")
def run(config, start, end, list_cases):
    """Run causal discovery analysis."""
    from fastcausal.pipeline.config import load_config
    from fastcausal.pipeline.batch import run_batch

    cfg = load_config(config)
    run_batch(cfg, start=start, end=end, list_cases=list_cases)


@main.command()
@click.option("--config", required=True, type=click.Path(exists=True), help="Path to config.yaml")
def paths(config):
    """Compute path effect sizes and generate heatmaps."""
    from fastcausal.pipeline.config import load_config
    from fastcausal.pipeline.paths import run_paths

    cfg = load_config(config)
    run_paths(cfg)


@main.command()
@click.option("--config", required=True, type=click.Path(exists=True), help="Path to config.yaml")
@click.option("--mode", default="1wide", type=click.Choice(["1wide", "2wide", "3wide"]), help="Report layout mode")
@click.option("--stub", default="_label.png", help="Image filename suffix to include")
def report(config, mode, stub):
    """Generate analysis report document."""
    from fastcausal.pipeline.config import load_config
    from fastcausal.pipeline.report import run_report

    cfg = load_config(config)
    run_report(cfg, mode=mode, stub=stub)


@main.command()
@click.argument("datafile", type=click.Path(exists=True))
@click.option("--algorithm", default="gfci", type=click.Choice(["pc", "fges", "gfci"]), help="Causal discovery algorithm")
@click.option("--alpha", default=0.05, type=float, help="Significance level")
@click.option("--penalty-discount", default=1.0, type=float, help="BIC penalty multiplier")
@click.option("--output", default=".", type=click.Path(), help="Output directory")
def analyze(datafile, algorithm, alpha, penalty_discount, output):
    """Quick single-file causal analysis."""
    import os
    import pandas as pd
    from fastcausal import FastCausal

    fc = FastCausal()
    df = fc.load_csv(datafile)

    kwargs = {}
    if algorithm in ("pc", "gfci"):
        kwargs["alpha"] = alpha
    if algorithm in ("fges", "gfci"):
        kwargs["penalty_discount"] = penalty_discount

    results, dg = fc.run_search(df, algorithm=algorithm, run_sem=False, **kwargs)

    os.makedirs(output, exist_ok=True)
    graph_path = os.path.join(output, os.path.splitext(os.path.basename(datafile))[0])
    if results["edges"]:
        fc.save_graph(dg, graph_path, plot_format="png")
        click.echo(f"Graph saved to: {graph_path}")

    click.echo(f"Edges found: {len(results.get('edges', []))}")
    for edge in results.get("edges", []):
        click.echo(f"  {edge}")
